language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew assemble

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true